### PR TITLE
added 'archive_branch' option to the GitHub Action

### PR DESCRIPTION
**Pull request by mattecapu**
Added an option to address Issue #46

### CODE REVIEW

**Comment by logankilpatrick** [comment]
Would be awesome to get this merged given the tool to re-name the default branch has rolled out across GitHub.

**Comment by timabbott** [comment]
Merged, sorry for the slow review!  This is a low-activity repository that thus is my job to manage, and a baby joined my family in November :).

**Comment by logankilpatrick** [comment]
Congrats! Hope your staying safe.

**Comment by mattecapu** [comment]
Thanks @timabbott! I appreciate the time you put in this, there was no hurry :) congrats for the kid!

**Comment by SaschaMann** [comment]
I've renamed the branch and added the new input to the workflow, but now this error occurs:

```
error: src refspec main does not match any.
error: failed to push some refs to '***github.com/JuliaCommunity/zulip-archive'
```

(see https://github.com/JuliaCommunity/zulip-archive/runs/2240461747?check_suite_focus=true)

The only reference to `master` that I can still find in this repo is in `github.py`:

https://github.com/zulip/zulip-archive/blob/ba5a49287c77663f814e23642f7e371549815104/github.py#L18-L21

I don't think that file is called from the action, but I might be wrong.

Do you have an idea what could cause this or how to fix it?

**Comment by mattecapu** [comment]
I guess it's caused by `delete_history` recreating the Git repo from scratch with the wrong name

**Pull request merged**
