### PR TITLE
logo: Update to use current Zulip logo.

### LINKED ISSUE #49: Zulip logo is outdated
https://github.com/zulip/zulip-archive/blob/bcd29a173500de778e70a304fc40cdffaec78803/assets/img/zulip2.png is still the green one.

### PR DESCRIPTION
**Pull request by Abhirup-99**
Fixes #49.

### CODE REVIEW

**Comment by Abhirup-99** [comment]
@rht please take a glance when free.

**Comment by rht** [comment]
LGTM. I confirmed it by looking at the file in https://github.com/Abhirup-99/zulip-archive/blob/fd51fb91115e376b0c49bd0c55b34ac8ae229a11/assets/img/zulip2.png, because GitHub diff doesn't actually render the new png.

**Comment by rht** [comment]
Speaking of which, the old png is ~2x smaller in byte size: https://github.com/zulip/zulip-archive/blob/f5f1c71ff46f51bfb6148b4795d6db40630e24bc/assets/img/zulip2.png. I wonder if the new 1.2 KB logo will result in the img source being displayed twice as large. See e.g. https://leanprover-community.github.io/archive/stream/113488-general/topic/request.20for.20tactic.html.

**Comment by Abhirup-99** [comment]
Yeah, it did increase the size. I would update it shortly with a smaller image.

**Comment by Abhirup-99** [comment]
@rht take a look when free. I have updated it to be of the same size now.

**Comment by timabbott** [comment]
Can we just use an SVG?

I think we should be setting the display size via CSS, rather than making a small / low quality image file.

**Comment by Abhirup-99** [comment]
@timabbott I have replaced it with a svg. The svg is taken from https://zulip.com/static/images/favicon.svg?v=4

**Comment by timabbott** [comment]
Merged, thanks @Abhirup-99!  Can you post a quick screenshot in #design on chat.zulip.org of what an archive with this looks like?  I feel like we should do a bit more looking at the size question from a design perspective.

**Comment by Abhirup-99** [comment]
Sure,on way. The previous one was 15*15, the current one is 20*20.

**Pull request merged**
