### PR TITLE
Specify that charset of pages is utf-8

### PR DESCRIPTION
**Pull request by Nemo157**

### CODE REVIEW

**Comment by Nemo157** [comment]
Sorry, looks like the `gh` CLI doesn't like making PRs to forks :frowning:

**Comment by timabbott** [comment]
Is that a change we should have in upstream?  It seems likely...

**Comment by Nemo157** [comment]
Maybe, but it looks like the code has significantly changed since rust-lang's fork. Checking the Lean Prover archive linked from the readme that is sending a charset meta tag back, I think it may be an issue rust-lang brought on itself by using a much simpler markdown->html converter that doesn't add the meta tag automatically.

**Comment by robertylewis** [comment]
Yes, this is already done upstream: https://github.com/zulip/zulip-archive/blob/master/layouts/archive.html

**Pull request closed without merging**
