### PR TITLE
Apply Black to the repo

### PR DESCRIPTION
**Pull request by rht**

### CODE REVIEW

**Comment by neiljp** [comment]
@rht `black` is fairly reliable in translating the formatting, but you might consider doing this in stages to separate the quote transition from the reformatting, and consider prep commits to do things like simplify strings, if relevant. This was done in `zulip/zulip` and the same approach is being taken in the other repos.

**Comment by rht** [comment]
OK split into without quote normalization and with quote normalization.

> consider prep commits to do things like simplify strings

What kind of simplification is this specifically?

**Comment by neiljp** [comment]
Re string simplification: having looked through the first diff there seems to be no cases of this, but black joins lines where strings are implicitly combined, without handling the adjacent end/start quotes, ie. it doesn't merge code like `"string1" " string2"`.

**Comment by timabbott** [comment]
Yeah, I think we don't have enough long strings to have that failure mode.  Merged, thanks @rht!

**Pull request merged**
