### PR TITLE
fix python version

### LINKED ISSUE #73: Fail to archive due to Python version too low
https://github.com/tisonkun/zulip-archive/runs/4997354269?check_suite_focus=true

```
2022-01-30T15:05:17.2351750Z ##[group]Run zulip/zulip-archive@master
2022-01-30T15:05:17.2352844Z with:
2022-01-30T15:05:17.2353274Z   zulip_organization_url: ***
2022-01-30T15:05:17.2353593Z   zulip_bot_email: ***
2022-01-30T15:05:17.2353890Z   zulip_bot_key: ***
2022-01-30T15:05:17.2354295Z   github_personal_access_token: ***
2022-01-30T15:05:17.2354529Z   delete_history: true
2022-01-30T15:05:17.2354755Z   archive_branch: gh-pages
2022-01-30T15:05:17.2354991Z ##[endgroup]
2022-01-30T15:05:17.2600562Z ##[command]/usr/bin/docker run --name eaf078a84fb3749efb334b15627788c66_eca44b --label 84217e --workdir /github/workspace --rm -e INPUT_ZULIP_ORGANIZATION_URL -e INPUT_ZULIP_BOT_EMAIL -e INPUT_ZULIP_BOT_KEY -e INPUT_GITHUB_PERSONAL_ACCESS_TOKEN -e INPUT_DELETE_HISTORY -e INPUT_ARCHIVE_BRANCH -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/zulip-archive/zulip-archive":"/github/workspace" 84217e:af078a84fb3749efb334b15627788c66  "***" "***" "***" "***" "true" "gh-pages"
2022-01-30T15:05:17.5575442Z   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
2022-01-30T15:05:17.5576823Z                                  Dload  Upload   Total   Spent    Left  Speed
2022-01-30T15:05:17.5582860Z 
2022-01-30T15:05:17.7092965Z   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
2022-01-30T15:05:17.7103161Z 100 2548k  100 2548k    0     0  16.3M      0 --:--:-- --:--:-- --:--:-- 16.3M
2022-01-30T15:05:17.7541038Z ERROR: This script does not work on Python 3.6 The minimum supported Python version is 3.7. Please use https://bootstrap.pypa.io/pip/3.6/get-pip.py instead.
```

### PR DESCRIPTION
**Pull request by tisonkun**
This closes #73.

Let me try to test it.

### CODE REVIEW

**Comment by tisonkun** [comment]
Verified at https://github.com/tisonkun/zulip-archive/actions/runs/1769064952.

**Comment by rht** [comment]
We better upgrade the Python version to be >=3.9. This needs the Dockerfile image to be updated. cc @hackerkid

**Comment by tisonkun** [comment]
@rht as our readme recommends users rely on master, I tend to fix the problem first and stop other instance like rust-lang/zulip_archive from failure.

I'm glad to see whether I can help upgrade the Python version later then.

**Comment by mattecapu** [comment]
> @rht as our readme recommends users rely on master, I tend to fix the problem first and stop other instance like rust-lang/zulip_archive from failure.
> 
> I'm glad to see whether I can help upgrade the Python version later then.

Strong agree with this.

**Review by hackerkid — APPROVED** [review]

**Comment by hackerkid** [comment]
Yeah. We should merge this first. I have created an issue for updating the Docker image at https://github.com/zulip/zulip-archive/issues/75

**Comment by rht** [comment]
I made #76, which I have already tested to be working at https://rht.github.io/zulip-archive-sample.

**Comment by timabbott** [comment]
Closing in favor of #76, thanks!

**Comment by tisonkun** [comment]
Thanks for fixing the issue :)

**Pull request closed without merging**
